import AppForm from '../app-components/Form/AppForm';

Vue.component('registration-form', {
    mixins: [AppForm],
    props: [
        'city',
        'careers',
        'experience',
        'looking',
        'statuses',
        'genders',
        'looking_roles',
        'accept_roles',
        'dances',
        'martial_arts',
        'instruments',
        'languages',
        'ethnicities',
        'nationalities',
        'voice_vocals',
        'tattoos',
        'sports',
    ],
    data: function() {
        return {
            form: {
                name:  '' ,
                email:  '' ,
                hometown:  '' ,
                birthday:  '' ,
                current_career:  '' ,
                has_agency:  false ,
                agency_name:  '' ,
                want_agency:  false ,
                your_experience:  '' ,
                searching_for:  '' ,
                youtube_link:  '' ,
                facebook_link:  '' ,
                instagram_link:  '' ,
                tiktok_link:  '' ,
                weight:  '' ,
                height:  '' ,
                type:  '' ,
                status:  '' ,
                enabled:  false ,
                bio:  '' ,
                city_id: '',
                careers: '',
                experience: '',
                looking: '',
                looking_roles: '',
                accept_roles: '',
                dances: '',
                martial_arts: '',
                instruments: '',
                speaking_languages: '',
                ethnicities: '',
                nationalities: '',
                voice_vocals: '',
                tattoos: '',
                sports: '',
                statuses: '',
                genders: '',
                chest: '',
                hip: '',
                waist: '',
                shoes: '',
                address:'',
                parent_name: '',
            },
            mediaCollections: ['gallery', 'cover']
        }
    }

});